#!/bin/sh

ZT_BIN_DIR="/usr/sbin"
ZT_HOME_DIR="/var/lib/zerotier-one"

# echo "ZeroTier home dir = /var/lib/zerotier-one" > $SYNOPKG_TEMP_LOGFILE

echo Copying ZeroTier files...
mkdir -p ${ZT_BIN_DIR}

# 
machine_type=$(uname -m)
if [ ${machine_type} == "x86_64" ]; then
        mv ${SYNOPKG_PKGDEST}/bin/zerotier-one.x86_64 ${SYNOPKG_PKGDEST}/bin/zerotier-one
else
        mv ${SYNOPKG_PKGDEST}/bin/zerotier-one.armv7 ${SYNOPKG_PKGDEST}/bin/zerotier-one
fi

# copy zerotier-one
rm -f ${ZT_BIN_DIR}/zerotier-one
cp -f ${SYNOPKG_PKGDEST}/bin/zerotier-one ${ZT_BIN_DIR}/zerotier-one
chmod 755 ${ZT_BIN_DIR}/zerotier-one

rm -f ${ZT_BIN_DIR}/zerotier-cli
rm -f ${ZT_BIN_DIR}/zerotier-idtool
ln -s ${SYNOPKG_PKGDEST}/bin/zerotier-one ${ZT_BIN_DIR}/zerotier-cli
ln -s ${SYNOPKG_PKGDEST}/bin/zerotier-one ${ZT_BIN_DIR}/zerotier-idtool
chmod 755 ${ZT_BIN_DIR}/zerotier-cli
chmod 755 ${ZT_BIN_DIR}/zerotier-idtool

mkdir -p ${ZT_HOME_DIR}
rm -f ${ZT_HOME_DIR}/zerotier-one
rm -f ${ZT_HOME_DIR}/zerotier-cli
rm -f ${ZT_HOME_DIR}/zerotier-idtool
ln -s ../../..${ZT_BIN_DIR}/zerotier-one ${ZT_HOME_DIR}/zerotier-one
ln -s ../../..${ZT_BIN_DIR}/zerotier-one ${ZT_HOME_DIR}/zerotier-cli
ln -s ../../..${ZT_BIN_DIR}/zerotier-one ${ZT_HOME_DIR}/zerotier-idtool

# proxy service (provides service for UI in DSM)
cp -f ${SYNOPKG_PKGDEST}/bin/ztui_server.js ${ZT_HOME_DIR}/ztui_server.js
cp -f ${SYNOPKG_PKGDEST}/bin/reset.sh ${ZT_HOME_DIR}/reset.sh
cp -f ${SYNOPKG_PKGDEST}/bin/start.sh ${ZT_HOME_DIR}/start.sh
cp -f ${SYNOPKG_PKGDEST}/bin/tun.sh ${ZT_HOME_DIR}/tun.sh
cp -f ${SYNOPKG_PKGDEST}/bin/ztui_watchdog.sh ${ZT_HOME_DIR}/ztui_watchdog.sh
cp -f ${SYNOPKG_PKGDEST}/bin/package.json ${ZT_HOME_DIR}/package.json

# start zt ui proxy server
cd /var/lib/zerotier-one
npm install

# load TUN kernel module
SERVICE="zerotier"
ZEROTIER_MODULE="tun.ko"
BIN_SYNOMODULETOOL="/usr/syno/bin/synomoduletool"

# Make device if not present (not devfs)
if ( [ ! -c /dev/net/tun ] ) then
		# Make /dev/net directory if needed
		if ( [ ! -d /dev/net ] ) then
    		mkdir -m 755 /dev/net
		fi
		mknod /dev/net/tun c 10 200
fi

# Load TUN kernel module
if [ -x ${BIN_SYNOMODULETOOL} ]; then
	$BIN_SYNOMODULETOOL --insmod $SERVICE ${ZEROTIER_MODULE}
else
	/sbin/insmod /lib/modules/${ZEROTIER_MODULE}
fi

exit 0
