#!/bin/sh

ZT_BIN_DIR="/usr/sbin"
ZT_HOME_DIR="/var/lib/zerotier-one"

rm -f ${ZT_HOME_DIR}/zerotier-one
rm -f ${ZT_HOME_DIR}/zerotier-cli
rm -f ${ZT_HOME_DIR}/zerotier-idtool
rm -f ${ZT_BIN_DIR}/zerotier-cli
rm -f ${ZT_BIN_DIR}/zerotier-idtool
rm -f ${ZT_BIN_DIR}/zerotier-one
rm -rf ${ZT_HOME_DIR}/iddb.d
rm -rf ${ZT_HOME_DIR}/updates.d
rm -rf ${ZT_HOME_DIR}/networks.d
rm -f ${ZT_HOME_DIR}/zerotier-one.port

# proxy service (provides service for UI in DSM)
rm -rf ${ZT_HOME_DIR}/ztui_server.js
rm -rf ${ZT_HOME_DIR}/reset.sh
rm -rf ${ZT_HOME_DIR}/start.sh
rm -rf ${ZT_HOME_DIR}/package.json

cd /var/lib/zerotier-one
for package in `ls node_modules`; do npm uninstall $package; done;

exit 0
