#!/bin/sh

INSTALL_DIR="/usr/local/${PACKAGE}"
ZT_HOMEDIR="/var/lib/zerotier-one"

echo "$(date) UNINSTALL: killing zerotier-one and watchdog" >> /opt/var/log/zerotier-one.log ;
killall zerotier-one ;
pkill -f "ztui_watchdog" ;
echo "$(date) UNINSTALL: removing /var/lib/zerotier-one (where identities are kept)" >> /opt/var/log/zerotier-one.log ;
# remove all files except for identity files (for future convenience)
find ${ZT_HOMEDIR} -type f ! -name 'identity.*' -delete
rm -rf ${ZT_HOMEDIR}/controller.d
rm -rf ${ZT_HOMEDIR}/iddb.d
rm -rf ${ZT_HOMEDIR}/networks.d
echo "$(date) UNINSTALL: removing old symlinks" >> /opt/var/log/zerotier-one.log ;
rm -f ${INSTALL_DIR}
# nginx de-config
echo "$(date) UNINSTALL: removing nginx reverse proxy config" >> /opt/var/log/zerotier-one.log ;
rm -f /usr/local/etc/nginx/conf.d/dsm.zerotier.conf
# remove control scrip
rm -f /etc/init.d/zerotier
# TODO: check devicemap and remove all ls /etc/sysconfig/network-scripts entries

exit 0
