#!/bin/sh

ZT_BIN_DIR="/usr/sbin"
ZT_HOME_DIR="/var/lib/zerotier-one"

rm -f ${ZT_HOME_DIR}/zerotier-one
rm -f ${ZT_HOME_DIR}/zerotier-cli
rm -f ${ZT_HOME_DIR}/zerotier-idtool
rm -f ${ZT_BIN_DIR}/zerotier-cli
rm -f ${ZT_BIN_DIR}/zerotier-idtool
rm -f ${ZT_BIN_DIR}/zerotier-one
rm -rf ${ZT_HOME_DIR}/iddb.d
rm -rf ${ZT_HOME_DIR}/updates.d
rm -f ${ZT_HOME_DIR}/zerotier-one.port

rm -rf ${ZT_HOME_DIR}/reset.sh
rm -rf ${ZT_HOME_DIR}/tun.sh
rm -rf ${ZT_HOME_DIR}/ztui_watchdog.sh

cp -f /var/lib/zerotier-one/del_route_link_down.sh.original /usr/libexec/net/if_link_down/del_route_link_down.sh
rm -rf /var/lib/zerotier-one/del_route_link_down.sh.original

exit 0
