#!/bin/sh

ZT_BIN_DIR="/usr/sbin"
ZT_HOME_DIR="/var/lib/zerotier-one"

echo Copying ZeroTier files...
mkdir -p ${ZT_BIN_DIR}

mtype=$(uname -m)
if [ ${mtype} == 'x86_64' ];
	then
		mv ${SYNOPKG_PKGDEST}/bin/zerotier-one.x86_64 ${SYNOPKG_PKGDEST}/bin/zerotier-one
elif [[ ${mtype} == 'i386' ]] || [[ ${mtype} == 'i486' ]] || [[ ${mtype} == 'i586' ]] || [[ ${mtype} == 'i686' ]];
	then
		mv ${SYNOPKG_PKGDEST}/bin/zerotier-one.i686 ${SYNOPKG_PKGDEST}/bin/zerotier-one
else
        mv ${SYNOPKG_PKGDEST}/bin/zerotier-one.armv7 ${SYNOPKG_PKGDEST}/bin/zerotier-one
fi

# copy zerotier-one
rm -f ${ZT_BIN_DIR}/zerotier-one
cp -f ${SYNOPKG_PKGDEST}/bin/zerotier-one ${ZT_BIN_DIR}/zerotier-one
chmod 755 ${ZT_BIN_DIR}/zerotier-one

rm -f ${ZT_BIN_DIR}/zerotier-cli
rm -f ${ZT_BIN_DIR}/zerotier-idtool
ln -s ${SYNOPKG_PKGDEST}/bin/zerotier-one ${ZT_BIN_DIR}/zerotier-cli
ln -s ${SYNOPKG_PKGDEST}/bin/zerotier-one ${ZT_BIN_DIR}/zerotier-idtool
chmod 755 ${ZT_BIN_DIR}/zerotier-cli
chmod 755 ${ZT_BIN_DIR}/zerotier-idtool

mkdir -p ${ZT_HOME_DIR}
rm -f ${ZT_HOME_DIR}/zerotier-one
rm -f ${ZT_HOME_DIR}/zerotier-cli
rm -f ${ZT_HOME_DIR}/zerotier-idtool
ln -s ../../..${ZT_BIN_DIR}/zerotier-one ${ZT_HOME_DIR}/zerotier-one
ln -s ../../..${ZT_BIN_DIR}/zerotier-one ${ZT_HOME_DIR}/zerotier-cli
ln -s ../../..${ZT_BIN_DIR}/zerotier-one ${ZT_HOME_DIR}/zerotier-idtool

rm -rf ${ZT_HOME_DIR}/devicemap

cp -f ${SYNOPKG_PKGDEST}/bin/ztui_watchdog.sh ${ZT_HOME_DIR}/ztui_watchdog.sh

# nginx proxy config
cp -f ${SYNOPKG_PKGDEST}/dsm/dsm.zerotier.conf /usr/local/etc/nginx/conf.d/dsm.zerotier.conf
# for nginx to reload new reverse proxy conf file
nginx -s reload

# load TUN kernel module
SERVICE="zerotier"
ZEROTIER_MODULE="tun.ko"
BIN_SYNOMODULETOOL="/usr/syno/bin/synomoduletool"

# Make device if not present (not devfs)
if ( [ ! -c /dev/net/tun ] ) then
		# Make /dev/net directory if needed
		if ( [ ! -d /dev/net ] ) then
    		mkdir -m 755 /dev/net
		fi
		mknod /dev/net/tun c 10 200
fi

# Load TUN kernel module
if [ -x ${BIN_SYNOMODULETOOL} ]; then
	$BIN_SYNOMODULETOOL --insmod $SERVICE ${ZEROTIER_MODULE}
else
	/sbin/insmod /lib/modules/${ZEROTIER_MODULE}
fi

exit 0
