#! /bin/sh

# traditional uninstall

rm -f /var/lib/zerotier-one/zerotier-one
rm -f /var/lib/zerotier-one/zerotier-cli
rm -f /var/lib/zerotier-one/zerotier-idtool
rm -f /usr/sbin/zerotier-cli
rm -f /usr/sbin/zerotier-idtool
rm -f /usr/sbin/zerotier-one
rm -rf /var/lib/zerotier-one/iddb.d
rm -rf /var/lib/zerotier-one/updates.d
rm -rf /var/lib/zerotier-one/networks.d
rm -f /var/lib/zerotier-one/zerotier-one.port

# control and startup scripts

rm -rf start-stop-status.sh /var/lib/zerotier-one/start-stop-status
rm -rf zerotierone.sh /usr/local/etc/rc.d/zerotierone.sh